# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-05 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eveonline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sigtracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.CharField(default=b'', max_length=254)),
                ('system', models.CharField(default=b'', max_length=254)),
                ('destination', models.CharField(default=b'', max_length=254)),
                ('lifetime_status', models.CharField(default=b'', max_length=254)),
                ('mass_status', models.CharField(default=b'', max_length=254)),
                ('ships_size', models.CharField(default=b'', max_length=254)),
                ('notes', models.CharField(default=b'', max_length=254)),
                ('through_dest', models.CharField(default=b'', max_length=254)),
                ('post_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('eve_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eveonline.EveCharacter')),
            ],
            options={
                'ordering': ['post_time'],
            },
        ),
    ]
